### PR TITLE
configured graphql plugin and rendered graphql schema under reference

### PR DESCRIPTION
**Pull request by devcer**
Fixes https://github.com/interledger/rafiki.dev/issues/5

### CODE REVIEW

**Comment by devcer** [comment]
Screenshot 2022-10-11 at 11 46 36 PM
This is how it is going to look. @AlexLakatos I have listed the schema under `docs/reference`. let me know if this has to be under something else.

**Comment by adrianhopebailie** [comment]
Thanks for the contrib @devcer 

I presume everything under `reference` is autogen?
Is there a way to insert a comment or something to prevent people trying manually edit them?

Also, can we put those through a linter or tidy-html to make the HTML easier to read and a consistent format? 
It will help later when these pages need to be diffed

**Comment by devcer** [comment]
@adrianhopebailie Thats correct. everything under `reference` is autogenerated.  I will add a comment saying `/* Please do not edit this file. Autogenerated using "docs:graphql:generate" script`.

Regarding linting, should we use this? `https://docusaurus.io/docs/api/misc/@docusaurus/eslint-plugin` I can submit a separate PR that can go to main before this PR. what do you think?

**Comment by devcer** [comment]
Apparently, the comment will be overridden whenever we generate a new version of reference docs. We can create `contributions.md` and add the instructions there.

**Comment by AlexLakatos** [comment]
Thank you so much for adding this!

**Pull request merged**
